# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0e7d900f9fe41949cb96305697bbd3c0adc798dc8185ea21ae1251c9e0370a3ea54698e10711e46596b89efef0f96d74f7f9a48ef85b7f14f25890603c503dca

test:
  secret_key_base: d17f377217e35eee2d5fcfd262a740778563283fe19ccf8874e600bb72cb070eeb3717c50d62e052d7fee51346f9c1dadb4db7e3b3307b5260cfdbc50956a7ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
